#!/usr/bin/env python3
# Copyright 2026 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerates the website's API reference page from the shipped type stubs.

The page claims to be the real surface, so it is generated from the same file
the type checker reads rather than maintained by hand. `tests/unit/test_docs.py`
fails if the committed page and a fresh run disagree.

    python scripts/generate_api_reference.py            # write the page
    python scripts/generate_api_reference.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUB = ROOT / "python" / "drasi" / "_drasi.pyi"
PAGE = ROOT / "website" / "content" / "docs" / "api" / "_index.md"

# Section comments in the stub, mapped to the headings used on the page.
TITLES = {
    "core": "Creating an engine",
    "lifecycle": "Lifecycle",
    "queries": "Queries",
    "components defined in Python": "Components defined in Python",
    "components provided by plugins": "Components provided by plugins",
    "metrics and schema": "Metrics and schema",
    "streaming": "Streaming",
    "plugins": "Plugins",
}

HEADER = """---
title: "API Reference"
linkTitle: "API Reference"
weight: 40
description: >
  Every member of the Drasi class, grouped by area.
---

<!-- Generated by scripts/generate_api_reference.py. Do not edit by hand. -->

This is the surface of `drasi.Drasi`. Each member has a blocking counterpart of the
same name on `drasi.sync.Drasi`, where the `Awaitable[...]` return becomes the value
itself and a `Stream` becomes an ordinary iterator — see [the blocking
API](../guides/blocking-api/).

The shapes referenced here (`SourceChange`, `QueryResultEvent`, `StateStore` and the
rest) are declared in `drasi.types`, described in the [typing guide](../guides/typing/).

{{% alert title="Generated from the shipped stubs" color="info" %}}
The tables below are generated from `python/drasi/_drasi.pyi`, the same file your type
checker and editor read, and a test fails if they fall out of step. They cannot drift
from what the package exposes.
{{% /alert %}}
"""

FOOTER = """
## Errors

Everything raised is a `DrasiError` or a subclass, each carrying a stable `code`. See
[error handling](../guides/error-handling/) for the hierarchy and the full list of
codes.

## Module-level members

| Member | Description |
| --- | --- |
| `drasi.__version__` | The installed package version |
| `drasi.host_info()` | Versions, target triple and available index backends |
| `drasi.ERROR_CODES` | Every error code this build can raise |
| `drasi.DRASI_CORE_VERSION` | The `drasi-core` version this wheel was built against |
| `drasi.DRASI_LIB_VERSION` | The `drasi-lib` version this wheel was built against |
| `drasi.DRASI_SDK_VERSION` | The plugin SDK version this wheel was built against |
"""


def _escape(text: str) -> str:
    """Type unions contain `|`, which would otherwise split a table cell."""
    return text.replace("|", "\\|")


def _signature(source: str, node: ast.FunctionDef | ast.AsyncFunctionDef) -> tuple[str, str]:
    segment = ast.get_source_segment(source, node) or ""
    head, _, returns = segment.rpartition("-> ")
    returns = returns.replace(": ...", "").strip()
    head = re.sub(r"\s+", " ", head).strip().removesuffix("->").strip()
    head = head.removeprefix("def ")
    head = head.replace("(self, ", "(").replace("(self)", "()").replace("(self", "(")
    head = head.removesuffix(":").rstrip()
    head = head.replace("( ", "(").replace(", )", ")")
    if head.endswith(",)"):
        head = head[:-2] + ")"
    return head, returns


def _decorated_with(node: ast.FunctionDef | ast.AsyncFunctionDef, name: str) -> bool:
    return any(getattr(decorator, "id", "") == name for decorator in node.decorator_list)


def render() -> str:
    source = STUB.read_text(encoding="utf-8")
    lines = source.splitlines()
    engine = next(
        node
        for node in ast.parse(source).body
        if isinstance(node, ast.ClassDef) and node.name == "Drasi"
    )

    out = [HEADER]
    group = "core"
    seen: list[str] = []
    for node in engine.body:
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        preceding = lines[node.lineno - 2] if node.lineno >= 2 else ""
        if preceding.strip().startswith("#"):
            group = preceding.strip("# ").strip()
        if node.name.startswith("__"):
            continue

        if group not in seen:
            seen.append(group)
            out.append(f"\n### {TITLES.get(group, group.title())}\n")
            out.append("| Member | Returns |")
            out.append("| --- | --- |")

        head, returns = _signature(source, node)
        if _decorated_with(node, "property"):
            head, note = head.split("(")[0], " _(property)_"
        elif _decorated_with(node, "staticmethod"):
            note = " _(static)_"
        else:
            note = ""
        out.append(f"| `{_escape(head)}`{note} | `{_escape(returns)}` |")

    return "\n".join(out) + "\n" + FOOTER


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if current != rendered:
            print(
                f"{PAGE.relative_to(ROOT)} is out of date.\n"
                "Run: python scripts/generate_api_reference.py",
                file=sys.stderr,
            )
            return 1
        print(f"{PAGE.relative_to(ROOT)} matches the stubs.")
        return 0

    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text(rendered, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
